//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by lensf.rc
//
#define IDS_DB_NEGATIVE                 1
#define IDS_DB_IMAGE_FILTER             2
#define IDD_NEG_ABOUT                   101
#define IDD_GEN_ABOUT                   101
#define IDD_RADIAL                      104
#define IDD_MASTER                      112
#define IDD_BUILD                       113
#define IDC_BUILD1UP                    144
#define IDC_BUILD2UP                    147
#define IDB_BUILD3UP                    149
#define IDB_BUILD4UP                    151
#define IDB_BUILD5UP                    153
#define IDB_BUILD6UP                    155
#define IDB_BUILD7UP                    157
#define IDB_BUILD8UP                    159
#define IDB_BUILD9UP                    161
#define IDB_BUILD10UP                   163
#define IDB_BUILD11UP                   165
#define IDB_BUILD12UP                   167
#define IDC_PREVIEW_UP                  169
#define IDB_STATIC_WIDTH                171
#define IDB_STATIC_NOSTREAKS            173
#define IDB_STATIC_NOSIDES              174
#define IDB_STATIC_ILLUMINATION         175
#define IDB_STATIC_COLOUR               177
#define IDB_STATIC_FACTOR               178
#define IDB_STATIC_ASPECT               179
#define IDB_STATIC_CHECKERBOARD         180
#define IDD_MORPH                       181
#define IDB_STATIC_FROMTO               187
#define IDB_STATIC_POSITION             188
#define IDB_STATIC_SIZEVARIATION        189
#define IDB_STATIC_LIGHTVARIATION       190
#define IDB_STATIC_NUMBER               191
#define IDB_STATIC_INTERACTION          192
#define IDB_SPLASHSCREEN                195
#define IDD_PHYSICS                     196
#define IDB_STATIC_ANIMATIONPATH        201
#define IDD_ANIMATION                   203
#define IDB_STATIC_MASTERBG             208
#define IDD_RENDERPARAMETERS            209
#define IDD_EDIT                        210
#define IDD_FNOISE                      211
#define IDB_MASTER                      213
#define IDD_COMPLAIN                    214
#define IDB_COMPLAIN                    215
#define IDB_ANIMATIONPOSDOWN            219
#define IDB_ANIMATIONPOSUP              220
#define IDB_ANIMATIONSHPDOWN            221
#define IDB_ANIMATIONSHPUP              222
#define IDB_ARROWDOWN                   223
#define IDB_BUILD                       224
#define IDB_EDIT                        225
#define IDB_EDIT_LOCKDOWN               226
#define IDB_EDIT_LOCKUP                 227
#define IDB_ELEMENTCOPY                 228
#define IDB_ELEMENTDELETE               229
#define IDB_ELEMENTNEW                  230
#define IDB_EXP                         231
#define IDB_EXP2                        232
#define IDB_EXP2_PUSHED                 233
#define IDB_EXP_PUSHED                  234
#define IDB_GENESISLOGO                 235
#define IDB_HYP                         236
#define IDB_HYP_PUSHED                  237
#define IDB_INFERNODOWN1                238
#define IDB_INFERNODOWN2                239
#define IDB_INFERNOUP1                  240
#define IDB_INFERNOUP2                  241
#define IDB_LIN                         242
#define IDB_LIN_PUSHED                  243
#define IDB_MAKE                        244
#define IDB_MAKE_BUTTON1                245
#define IDB_MAKE_BUTTON1B               246
#define IDB_MAKE_BUTTON2                247
#define IDB_MAKE_BUTTON2_1              248
#define IDB_MAKE_BUTTON2_1B             249
#define IDB_MAKE_BUTTON2_2              250
#define IDB_MAKE_BUTTON2_2B             251
#define IDB_MAKE_BUTTON2_3              252
#define IDB_MAKE_BUTTON2_3B             253
#define IDB_MAKE_BUTTON2_4              254
#define IDB_MAKE_BUTTON2_4B             255
#define IDB_MAKE_BUTTON2B               256
#define IDB_MAKE_BUTTON3                257
#define IDB_MAKE_BUTTON3B               258
#define IDB_MAKE_BUTTON4                259
#define IDB_MAKE_BUTTON4B               260
#define IDB_MAKE_BUTTON5                261
#define IDB_MAKE_BUTTON5B               262
#define IDB_MAKE_BUTTON6                263
#define IDB_MAKE_BUTTON6B               264
#define IDB_MAKE_BUTTON7                265
#define IDB_MAKE_BUTTON7B               266
#define IDB_MAKE_BUTTON8                267
#define IDB_MAKE_BUTTON8B               268
#define IDB_MASTERCANCEL                269
#define IDB_MASTERLOCK_DOWN             270
#define IDB_MASTERLOCK_UP               271
#define IDB_MASTEROK                    272
#define IDB_MORPH                       273
#define IDB_NOISE                       274
#define IDB_NOISE_PUSHED                275
#define IDB_NOISEDLG                    276
#define IDB_NORMALISE                   277
#define IDB_REGLOCKDOWN                 278
#define IDB_REGLOCKUP                   279
#define IDB_RESET                       280
#define IDB_RESETCURVE                  281
#define IDB_SHAPEEDIT                   282
#define IDB_SHAPELOAD                   283
#define IDB_SHAPEMAKE                   284
#define IDB_SHAPEMORPH                  285
#define IDB_SHAPENOISE                  286
#define IDB_SHAPESAVE                   287
#define IDB_SIN                         288
#define IDB_SIN_PUSHED                  289
#define IDB_SWAP                        290
#define IDB_SYSTEMCONFIG                291
#define IDB_SYSTEMLOAD                  292
#define IDB_SYSTEMNEW                   293
#define IDB_SYSTEMSAVE                  294
#define IDB_TURLOCKDOWN                 295
#define IDB_TURLOCKUP                   296
#define IDB_UNDO                        297
#define IDB_UPARROW                     298
#define IDB_RENDER                      300
#define IDB_CENTROID                    301
#define IDB_COLORISE                    302
#define IDB_COLOUR                      303
#define IDB_EXTERNAL                    304
#define IDB_HIGH                        305
#define IDB_INSIDE                      306
#define IDB_INTERNAL                    307
#define IDB_MASKEXT                     308
#define IDB_MASKINT                     309
#define IDB_MEDIUM                      310
#define IDB_MULTI                       311
#define IDB_NOMASK                      312
#define IDB_NONE                        313
#define IDB_NORMAL                      314
#define IDB_OUTSIDE                     315
#define IDB_RESIZE                      317
#define IDB_SINGLE                      318
#define IDB_RENDEREXIT                  319
#define IDB_CLOSE                       320
#define IDB_RENDERCONT                  322
#define IDB_EXIT                        323
#define IDR_ACCELERATOR                 324
#define IDB_REGISTER                    326
#define IDB_REGOK                       327
#define IDD_REGISTER                    328
#define IDD_FILEPREVIEW                 329
#define IDD_PROGRESS                    330
#define IDB_LOGO                        331
#define IDB_MASTERHELP                  332
#define IDC_ACTIVE                      1010
#define IDC_WRAP                        1011
#define IDC_Add                         1032
#define IDC_BUILD                       1033
#define IDC_Mul                         1034
#define IDC_New                         1035
#define IDC_Colour1                     1036
#define IDC_OPEN                        1036
#define IDC_Colour2                     1037
#define IDC_SAVE                        1037
#define IDC_EDIT                        1038
#define IDC_NewElement                  1038
#define IDC_RadialEditAlpha             1039
#define IDC_EditFlare                   1039
#define IDC_RadialEditRGB               1040
#define IDC_BuildFlare                  1040
#define IDC_AngularEditAlpha            1041
#define IDC_MorphElement                1041
#define IDC_AngularEditRGB              1042
#define IDC_DeleteElement               1042
#define IDC_ShapeEdit                   1043
#define IDC_MoveUP                      1043
#define IDC_RadialShapeEdit             1043
#define IDC_Mode1                       1044
#define IDC_MoveDown                    1044
#define IDC_Mode2                       1045
#define IDC_CopyElement                 1045
#define IDC_Mode3                       1046
#define IDC_SAVE2                       1046
#define IDC_PARAMETERS                  1046
#define IDC_Mode4                       1047
#define IDC_LinkButton                  1047
#define IDC_Intensity_EDIT              1048
#define IDC_DFLINK2                     1048
#define IDC_NIntensity_EDIT             1049
#define IDC_Size_EDIT                   1049
#define IDC_LMax_EDIT                   1050
#define IDC_Angle_EDIT                  1050
#define IDC_Size_EDIT2                  1050
#define IDC_LMin_EDIT                   1051
#define IDC_XPosition_EDIT              1051
#define IDC_T8                          1051
#define IDC_Size_EDIT3                  1051
#define IDC_DEFORMY2_EDIT               1051
#define IDC_NLocation_EDIT              1052
#define IDC_YPosition_EDIT              1052
#define IDC_T7                          1052
#define IDC_Size_EDIT4                  1052
#define IDC_MATERIALOBJECT1_EDIT        1052
#define IDC_NFalloff_EDIT               1053
#define IDC_Colourise_EDIT              1053
#define IDC_T6                          1053
#define IDC_Size_EDIT5                  1053
#define IDC_HUEFROM_EDIT                1053
#define IDC_ANIM2_EDIT                  1053
#define IDC_Mode5                       1054
#define IDC_AngleOffSet_EDIT            1054
#define IDC_T5                          1054
#define IDC_Size_EDIT6                  1054
#define IDC_Colourise_EDIT2             1054
#define IDC_HUETO_EDIT                  1054
#define IDC_LEVELS_EDIT                 1054
#define IDC_Mode6                       1055
#define IDC_T4                          1055
#define IDC_Occlusion_EDIT              1055
#define IDC_Size_EDIT7                  1055
#define IDC_Colourise_EDIT3             1055
#define IDC_Time_EDIT                   1055
#define IDC_INTFROM_EDIT                1055
#define IDC_Location_EDIT               1056
#define IDC_T3                          1056
#define IDC_Depth_EDIT                  1056
#define IDC_Size_EDIT8                  1056
#define IDC_Colourise_EDIT4             1056
#define IDC_Occl_EDIT                   1056
#define IDC_INTTO_EDIT                  1056
#define IDC_SIZEY1_EDIT                 1056
#define IDC_Falloff_EDIT                1057
#define IDC_T2                          1057
#define IDC_Size_EDIT9                  1057
#define IDC_Colourise_EDIT5             1057
#define IDC_Dpth_EDIT                   1057
#define IDC_MATERIALOBJECT2_EDIT        1057
#define IDC_DEFORMY1_EDIT               1057
#define IDC_DRAW_PREVIEW                1058
#define IDC_Size_EDIT10                 1058
#define IDC_Colourise_EDIT6             1058
#define IDC_MTIME_EDIT                  1058
#define IDC_Value1_EDIT                 1058
#define IDC_RENDEROBJECT2_EDIT          1058
#define IDC_INFERNO                     1058
#define IDC_ANIM1_EDIT                  1058
#define IDC_UNDO                        1059
#define IDC_T1                          1059
#define IDC_Falloff_EDIT3               1059
#define IDC_SI_LOCK                     1059
#define IDC_Size_EDIT11                 1059
#define IDC_COLOID_EDIT                 1059
#define IDC_Seed_EDIT                   1060
#define IDC_S4                          1060
#define IDC_Falloff_EDIT4               1060
#define IDC_Size_EDIT12                 1060
#define IDC_Occlusion_EDIT2             1060
#define IDC_COLMID_EDIT                 1060
#define IDC_SZLINK1                     1060
#define IDC_Repetitions_EDIT            1061
#define IDC_S3                          1061
#define IDC_Falloff_EDIT5               1061
#define IDC_COL_EDIT                    1061
#define IDC_Size_EDIT13                 1061
#define IDC_FIXX_EDIT                   1061
#define IDC_DFLINK1                     1061
#define IDC_Intensity_SPIN              1062
#define IDC_S2                          1062
#define IDC_Falloff_EDIT6               1062
#define IDC_NUM_EDIT                    1062
#define IDC_Size_EDIT14                 1062
#define IDC_Depth_EDIT2                 1062
#define IDC_NIntensity_SPIN             1063
#define IDC_Size_SPIN                   1063
#define IDC_S1                          1063
#define IDC_Colourise_EDIT7             1063
#define IDC_PREVIEW                     1064
#define IDC_Angle_SPIN                  1064
#define IDC_ANG_EDIT                    1064
#define IDC_Size_SPIN2                  1064
#define IDC_LMax_SPIN                   1065
#define IDC_XPosition_SPIN              1065
#define IDC_EDIT1                       1065
#define IDC_ANG2_EDIT                   1065
#define IDC_Size_SPIN3                  1065
#define IDC_DEFORMY2_SPIN               1065
#define IDC_LMin_SPIN                   1066
#define IDC_YPosition_SPIN              1066
#define IDC_EDIT3                       1066
#define IDC_XPOS_EDIT                   1066
#define IDC_Size_SPIN4                  1066
#define IDC_MATERIALOBJECT1_SPIN        1066
#define IDC_Location_SPIN               1067
#define IDC_Colourise_SPIN              1067
#define IDC_EDIT2                       1067
#define IDC_YPOS_EDIT                   1067
#define IDC_Size_SPIN5                  1067
#define IDC_HUEFROM_SPIN                1067
#define IDC_ANIM2_SPIN                  1067
#define IDC_NLocation_SPIN              1068
#define IDC_AngleOffSet_SPIN            1068
#define IDC_EDIT4                       1068
#define IDC_Int_EDIT                    1068
#define IDC_Size_SPIN6                  1068
#define IDC_Colourise_SPIN2             1068
#define IDC_HUETO_SPIN                  1068
#define IDC_LEVELS_SPIN                 1068
#define IDC_Falloff_SPIN                1069
#define IDC_EDIT5                       1069
#define IDC_Occlusion_SPIN              1069
#define IDC_Size_SPIN7                  1069
#define IDC_Colourise_SPIN3             1069
#define IDC_Time_SPIN                   1069
#define IDC_INTFROM_SPIN                1069
#define IDC_NFalloff_SPIN               1070
#define IDC_EDIT6                       1070
#define IDC_Falloff_SPIN3               1070
#define IDC_Depth_SPIN                  1070
#define IDC_Size_SPIN8                  1070
#define IDC_Colourise_SPIN4             1070
#define IDC_Occl_SPIN                   1070
#define IDC_INTTO_SPIN                  1070
#define IDC_SIZEY1_SPIN                 1070
#define IDC_Seed_SPIN                   1071
#define IDC_Falloff_SPIN4               1071
#define IDC_SZ_SPIN                     1071
#define IDC_Size_SPIN9                  1071
#define IDC_Colourise_SPIN5             1071
#define IDC_Dpth_SPIN                   1071
#define IDC_MATERIALOBJECT2_SPIN        1071
#define IDC_DEFORMY1_SPIN               1071
#define IDC_MAKESEED_EDIT               1071
#define IDC_PREVIEW_CURVE               1072
#define IDC_Falloff_SPIN5               1072
#define IDC_COL_SPIN                    1072
#define IDC_Size_SPIN10                 1072
#define IDC_Colourise_SPIN6             1072
#define IDC_RENDEROBJECT2_SPIN          1072
#define IDC_ANIM1_SPIN                  1072
#define IDC_Repetitions_SPIN            1073
#define IDC_Falloff_SPIN6               1073
#define IDC_NUM_SPIN                    1073
#define IDC_Size_SPIN11                 1073
#define IDC_SZ_SPIN2                    1073
#define IDC_COLOID_SPIN                 1073
#define IDC_CHECKER                     1074
#define IDC_Size_SPIN12                 1074
#define IDC_COL_SPIN2                   1074
#define IDC_COLMID_SPIN                 1074
#define IDC_RadialLock                  1075
#define IDC_ElementActive               1075
#define IDC_SPIN3                       1075
#define IDC_CHECKER2                    1075
#define IDC_Seed2_SPIN                  1075
#define IDC_Size_SPIN13                 1075
#define IDC_YPOS_EDIT2                  1075
#define IDC_FIXX_SPIN                   1075
#define IDC_AngularLock                 1076
#define IDC_SPIN2                       1076
#define IDC_ANG_SPIN                    1076
#define IDC_ReAlign                     1076
#define IDC_Size_SPIN14                 1076
#define IDC_Normalise                   1077
#define IDC_SPIN4                       1077
#define IDC_ANG2_SPIN                   1077
#define IDC_OffScreen                   1077
#define IDC_Size_EDIT15                 1077
#define IDC_Falloff_EDIT2               1078
#define IDC_LENSNAME                    1078
#define IDC_SPIN5                       1078
#define IDC_XPOS_SPIN                   1078
#define IDC_Size_SPIN15                 1078
#define IDC_NFalloff_EDIT2              1079
#define IDC_SPIN6                       1079
#define IDC_YPOS_SPIN                   1079
#define IDC_Size_EDIT16                 1079
#define IDC_REALTIME                    1079
#define IDC_FIXY_EDIT                   1079
#define IDC_Falloff_SPIN2               1080
#define IDC_COMBO                       1080
#define IDC_Int_SPIN                    1080
#define IDC_Size_SPIN16                 1080
#define IDC_Int_EDIT2                   1080
#define IDC_POLAR                       1080
#define IDC_FIXY_SPIN                   1080
#define IDC_MAKESEED_SPIN               1080
#define IDC_NFalloff_SPIN2              1081
#define IDC_Size_EDIT17                 1081
#define IDC_Int_SPIN2                   1081
#define IDC_ZSORT                       1081
#define IDC_RADIUSEDIT                  1081
#define IDC_ShapeEdit2                  1082
#define IDC_AngularShapeEdit            1082
#define IDC_Size_SPIN17                 1082
#define IDC_Seed2_SPIN2                 1082
#define IDC_MTIME_SPIN                  1082
#define IDC_RADIUSSPIN                  1082
#define IDC_ABSOLUTE                    1082
#define IDC_USEBACK                     1083
#define IDC_Size_EDIT18                 1083
#define IDC_Occlusion_SPIN2             1083
#define IDC_IM_EDIT                     1083
#define IDC_TOBACK                      1084
#define IDC_Size_SPIN18                 1084
#define IDC_Depth_SPIN2                 1084
#define IDC_RTP                         1084
#define IDC_IM_SPIN                     1084
#define IDC_FallOffLock                 1085
#define IDC_Size_EDIT19                 1085
#define IDC_Colourise_SPIN7             1085
#define IDC_Size_SPIN19                 1086
#define IDC_SWAP                        1086
#define IDC_Dist_EDIT                   1087
#define IDC_Size_EDIT20                 1087
#define IDC_RESET                       1087
#define IDC_OOID_EDIT                   1087
#define IDC_Dist_SPIN                   1088
#define IDC_Size_SPIN20                 1088
#define IDC_Value2_EDIT                 1088
#define IDC_OOID_SPIN                   1088
#define IDC_MASTERPREVIEW               1089
#define IDC_Size_EDIT21                 1089
#define IDC_Value1_SPIN                 1089
#define IDC_OMID_EDIT                   1089
#define IDC_DEFORMX2_EDIT               1089
#define IDC_DRAW_MPREVIEW               1090
#define IDC_Size_SPIN21                 1090
#define IDC_Value2_SPIN                 1090
#define IDC_OMID_SPIN                   1090
#define IDC_DEFORMX2_SPIN               1090
#define IDC_LIGHT                       1091
#define IDC_Size_EDIT22                 1091
#define IDC_DRAW_MPREVIEW2              1091
#define IDC_RESETC                      1091
#define IDC_FIXZ_EDIT                   1091
#define IDC_BUILDPREVIEW_GO             1092
#define IDC_Size_SPIN22                 1092
#define IDC_DRAW_MPREVIEW3              1092
#define IDC_FIXZ_SPIN                   1092
#define IDC_BUILDCHECKER                1093
#define IDC_Size_EDIT23                 1093
#define IDC_DRAW_MPREVIEW5              1093
#define IDC_SPIN1                       1094
#define IDC_Size_SPIN23                 1094
#define IDC_COL1                        1095
#define IDC_Size_EDIT24                 1095
#define IDC_Size_SPIN24                 1096
#define IDC_DRAW_MPREVIEW8              1096
#define IDC_SIZEX1_EDIT                 1096
#define IDC_BITMAPCONTAINER             1097
#define IDC_Size_EDIT25                 1097
#define IDC_DRAW_MPREVIEW9              1097
#define IDC_SIZEX1_SPIN                 1097
#define IDTEST                          1098
#define IDC_Size_SPIN25                 1098
#define IDC_DEFORMX1_EDIT               1098
#define IDC_BUILDPREVIEW                1099
#define IDC_Size_EDIT26                 1099
#define IDC_Size_SPIN26                 1100
#define IDC_DEFORMX1_SPIN               1100
#define IDC_Size_EDIT27                 1101
#define IDC_CHECK1                      1102
#define IDC_Size_SPIN27                 1102
#define IDC_RenderReal                  1102
#define IDC_CHECK                       1102
#define IDC_Size_EDIT28                 1103
#define IDC_CD_EDIT                     1103
#define IDC_FREQ_EDIT                   1103
#define IDC_COMBOFROM                   1104
#define IDC_Size_SPIN28                 1104
#define IDC_CD_SPIN                     1104
#define IDC_FREQ_SPIN                   1104
#define IDC_COMBOTO                     1105
#define IDC_Size_EDIT29                 1106
#define IDC_Size_SPIN29                 1107
#define IDC_SZ_EDIT                     1108
#define IDC_Size_EDIT30                 1108
#define IDC_Size_SPIN30                 1109
#define IDC_NAMEEDIT                    1110
#define IDC_Seed2_EDIT                  1111
#define IDC_MORPH_PREVIEW               1112
#define IDC_MORPH_PREVIEW_WINDOW        1113
#define IDC_DRAW_MPREVIEW4              1113
#define IDC_Type                        1114
#define IDC_SMALLPREVIEW                1115
#define IDC_TOPREVIEW                   1116
#define IDC_FROMPREVIEW                 1117
#define IDC_LISTBOX                     1122
#define IDC_LISTEDIT                    1123
#define IDC_LISTBOX2                    1126
#define IDC_PHYSICS                     1126
#define IDC_SETLINK                     1126
#define IDC_PHYSICS2                    1127
#define IDC_SHAPE_KEYFRAME              1127
#define IDC_PHYSICS3                    1128
#define IDC_POSITION_KEYFRAME           1128
#define IDC_COPYFRAME                   1129
#define IDC_RENDERMATERIAL              1129
#define IDC_FORWARD                     1130
#define IDC_RENDERCOLOUR                1130
#define IDC_BACK                        1131
#define IDC_RENDERFIXED                 1131
#define IDC_ELEMENTLOAD                 1132
#define IDC_PCENTROID                   1132
#define IDC_ELEMENTSAVE                 1133
#define IDC_PFULL                       1133
#define IDC_PEDGES                      1134
#define IDC_AA1                         1135
#define IDC_LISTBOX3                    1136
#define IDC_MEGASCROLL                  1136
#define IDC_AA2                         1136
#define IDC_MBACK                       1137
#define IDC_AA3                         1137
#define IDC_MFORWARD                    1138
#define IDC_COMPZ                       1138
#define IDC_MMEGASCROLL                 1139
#define IDC_PROCESSZ                    1139
#define IDC_ONORMAL                     1140
#define IDC_OOVERWRITE                  1141
#define IDC_REALPREVIEW                 1144
#define IDC_PREVIEWRA1                  1146
#define IDC_PREVIEWRA2                  1147
#define IDC_LINKNAMES                   1148
#define IDC_RENDERLINK                  1149
#define IDC_RENDEROBJECT                1150
#define IDC_RENDEROBJECT1_EDIT          1151
#define IDC_RENDEROBJECT1_SPIN          1152
#define IDC_HUE                         1153
#define IDC_INT                         1154
#define IDC_PLOCK                       1155
#define IDC_APV                         1156
#define IDC_PSINGLE                     1157
#define IDC_INFERNOPREVIEW              1157
#define IDC_FTYPE1                      1158
#define IDC_FTYPE2                      1159
#define IDC_SIZEX2_EDIT                 1161
#define IDC_SIZEY2_EDIT                 1162
#define IDC_SIZEX2_SPIN                 1163
#define IDC_SIZEY2_SPIN                 1164
#define IDC_SZLINK2                     1165
#define IDC_NOISECHECKER                1166
#define IDC_RenderPreview               1170
#define IDC_ImageSizeEdit               1171
#define IDC_ImageSizeSpin               1172
#define IDC_RenderPreviewButton         1173
#define IDC_RenderClipSel               1174
#define IDC_RenderClipOutside           1175
#define IDC_RenderNoClip                1176
#define IDC_ScaleEdit                   1177
#define IDC_AntiNormal                  1177
#define IDC_BrightEdit                  1178
#define IDC_AntiMedium                  1178
#define IDC_XEdit                       1179
#define IDC_REG_CLOSE                   1179
#define IDC_YEdit                       1180
#define IDC_REG2                        1180
#define IDC_ScaleSpin                   1181
#define IDC_AntiHigh                    1181
#define IDC_REG1                        1181
#define IDC_BrightSpin                  1182
#define IDC_SERIAL                      1182
#define IDC_XSpin                       1183
#define IDC_YSpin                       1184
#define IDC_SourceSel                   1185
#define IDC_SourceCen                   1186
#define IDC_Centroid                    1186
#define IDC_SourceAll                   1187
#define IDC_SourceInt                   1187
#define IDC_SourceCol                   1188
#define IDC_SourceEdges                 1189
#define IDC_SourceExt                   1189
#define IDC_ExtEdit                     1190
#define IDC_Colourise                   1191
#define IDC_ColouriseEdit               1191
#define IDC_ColouriseSpin               1192
#define IDC_NoMask                      1192
#define IDC_CLOSE                       1193
#define IDC_ExtSpin                     1194
#define IDC_Col2                        1195
#define IDC_ToleranceEdit               1196
#define IDC_ToleranceSpin               1197
#define IDC_HSCROLLBAR                  1198
#define IDC_VSCROLLBAR                  1199
#define IDC_ScaleToFit                  1200
#define IDC_RenderExit                  1201
#define IDC_EdgeEdit                    1202
#define IDC_IntEdit                     1202
#define IDC_EdgeSpin                    1203
#define IDC_IntSpin                     1203
#define IDC_Multi                       1204
#define IDC_ColEdit                     1205
#define IDC_ColSpin                     1206
#define IDC_MaskOut                     1207
#define IDC_MaskIn                      1208
#define IDC_MASTER_OK                   1208
#define IDC_MASTER_CANCEL               1209
#define IDC_Render                      1209
#define IDC_BUILD_OK                    1210
#define IDC_BUILD_CANCEL                1211
#define IDC_EDIT_OK                     1212
#define IDC_EDIT_CANCEL                 1213
#define IDC_INFERNO_OK                  1214
#define IDC_INFERNO_CANCEL              1215
#define IDC_MORPH_OK                    1216
#define IDC_MORPH_CANCEL                1217
#define IDC_PREVIEW_DIB                 1218
#define IDC_BUTTON1                     1219
#define IDC_GENERATE_THUMBNAILS         1219
#define IDC_EVAL                        1219
#define IDC_PROGRESS_TEXT               1220
#define IDC_PROGRESS_BAR                1221
#define IDC_HELPB                       1222
#define IDC_BACKGROUND                  1999
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        333
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1223
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
